### ISSUE TITLE
Unable to promote "page" content type to the home page

### ISSUE THREAD

**Issue by NoniH** [govau/dta-website-rebuild#165] opened 2018-03-08 04:14 UTC
"Page" content should be able to promoted to the home page for promotional purposes. 

Currently nothing happens when "promote to page" is selected

**Comment by imperator99** [comment] 2018-03-08 05:13
Duplicate of https://github.com/govau/dta-website-rebuild/issues/166.

**Closed by imperator99** 2018-03-08 05:13 UTC
Labels: duplicate
