### ISSUE TITLE
No side nav on "page" content type

### ISSUE THREAD

**Issue by NoniH** [govau/dta-website-rebuild#144] opened 2018-03-06 05:59 UTC
e.g. https://dta-website-rebuild-develop.apps.y.cld.gov.au/how-services-are-assessed

<img width="880" alt="screen shot 2018-03-06 at 4 58 49 pm" src="https://user-images.githubusercontent.com/21048750/37016323-ba869212-215f-11e8-8290-7a89879be8b2.png">

**Comment by imperator99** [comment] 2018-03-07 04:42
Duplicate of https://github.com/govau/dta-website-rebuild/issues/115.

**Closed by imperator99** 2018-03-07 04:42 UTC
