### ISSUE TITLE
dta-gov-au theme is not pinned by composer.lock

### ISSUE THREAD

**Issue by aeijdenberg** [govau/dta-website-rebuild#446] opened 2018-07-19 03:41 UTC
dta-gov-au theme does not appear to be pinned by either composer.json or composer.lock which I think means that we are always deploying from head.

Determine if this is best practice, or whether we can pin this so that what it is deployed to prod will match what has been tested in staging.

Investigate the same for other modules.

**Comment by imperator99** [comment] 2018-07-23 00:20
Possible duplicate of https://github.com/govau/dta-gov-au/issues/240.

**Comment by imperator99** [comment] 2018-07-24 00:02
Resolved by https://github.com/govau/dta-website-rebuild/pull/450.

**Closed by imperator99** 2018-07-24 00:02 UTC
Labels: deployment, duplicate
