### ISSUE TITLE
Change related links to be related cards on ALL content types

### ISSUE THREAD

**Issue by NoniH** [govau/dta-website-rebuild#147] opened 2018-03-07 01:20 UTC
Some pages still have the related links list rather than the related content cards that we discussed. 

e.g. on this page content

https://dta-website-rebuild-develop.apps.y.cld.gov.au/node/103/edit

**Comment by imperator99** [comment] 2018-03-07 23:05
@NoniH I don't understand what you mean here. Do you want to be able to update the heading for the related content links, or do you want them formatted as cards all the time? Just because this page doesn't have any related links so I am unsure what the problem is.

**Comment by NoniH** [comment] 2018-03-07 23:27
![screen shot 2018-03-08 at 10 22 23 am](https://user-images.githubusercontent.com/21048750/37124164-3efc3d2e-22bb-11e8-9075-1d530c28e3d9.png)

This page is a better example: https://dta-website-rebuild-develop.apps.y.cld.gov.au/help-and-advice/learning-and-development/start-your-digital-career-government

The related links is not showing up as cards

**Comment by NoniH** [comment] 2018-03-08 22:25
Another example is this page: https://dta-website-rebuild-develop.apps.y.cld.gov.au/help-and-advice/guides-and-tools-building-digital-services

![screen shot 2018-03-09 at 9 23 00 am](https://user-images.githubusercontent.com/21048750/37180036-c11083d6-237b-11e8-876e-09a4bea42eca.png)

**Comment by imperator99** [comment] 2018-03-15 01:13
@NoniH in order to complete this change any 'links to other pages' will need to be re-added as 'related links' (as per your request). As currently set up it is impossible to create cards in the same style as on landing page nodes because the 'link' field type does not have an equivalent 'summary' field, only a title.

**Comment by NoniH** [comment] 2018-03-15 01:28
I know we will have to re do all the related links. That's fine. Just change it and we can go from there

**Comment by imperator99** [comment] 2018-03-15 02:04
Resolved by https://github.com/govau/dta-website-rebuild/pull/178.

**Closed by imperator99** 2018-03-15 02:04 UTC
Labels: enhancement
