### ISSUE TITLE
Need to be able to move all published content to a complete state of being unpublished

### ISSUE THREAD

**Issue by NoniH** [govau/dta-website-rebuild#214] opened 2018-03-20 23:46 UTC
Many published pages have had 5 or 6 revisions since they were published. Need to be able to unpublish these pages without losing the revisions.

**Comment by imperator99** [comment] 2018-03-25 21:43
Duplicate of https://github.com/govau/dta-website-rebuild/issues/151.

**Closed by imperator99** 2018-03-25 21:43 UTC
Labels: enhancement
