### ISSUE TITLE
URGENT: Recruiter Box showing on random pages

### ISSUE THREAD

**Issue by nigelbartlett** [govau/dta-website-rebuild#237] opened 2018-03-29 00:58 UTC
RecruiterBox is showing on landing pages it's not meant to, eg: Learning and Development , Digital Service Standard, Panels and Arrangements. 
![screen shot 2018-03-29 at 11 45 26 am](https://user-images.githubusercontent.com/19921731/38063886-6c073386-3347-11e8-8c00-ff180be794af.png)

**Comment by imperator99** [comment] 2018-04-03 05:02
Duplicate of https://github.com/govau/dta-website-rebuild/issues/234.

**Closed by imperator99** 2018-04-03 05:02 UTC
Labels: duplicate
