### ISSUE TITLE
No option to publish L2 landing

### ISSUE THREAD

**Issue by NoniH** [govau/dta-website-rebuild#201] opened 2018-03-19 06:29 UTC
<img width="660" alt="screen shot 2018-03-19 at 5 28 21 pm" src="https://user-images.githubusercontent.com/21048750/37581063-fd0cacd0-2b9a-11e8-89e7-c492bc23284c.png">

Example from here: https://dta-website-rebuild-develop.apps.y.cld.gov.au/node/224/edit

**Comment by imperator99** [comment] 2018-03-19 21:14
Duplicate of https://github.com/govau/dta-website-rebuild/issues/196.

**Closed by imperator99** 2018-03-19 21:14 UTC
